services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./SERVE/ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    env_file:
      - ./SERVE/.env
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    # image: fastapitest:latest
    container_name: fastapillm
    ports:
      - 8000:8000
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   ports: 
  #     - "11434:11434"
  #   volumes:
  #     - "C:/Users/ryanc/.ollama:/root/.ollama"
  #   deploy:
  #     resources:
  #       - driver: nvidia
  #         count: all
  #         capabilities: [gpu]
